//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.web.Controls.FolderMain {
    
    
    public partial class LeftNavigationControl {
        
        /// <summary>
        /// UserInfoControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::project.web.Controls.FolderMain.UserInfoControl UserInfoControl1;
        
        /// <summary>
        /// LeftMenuControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::project.web.Controls.FolderMain.LeftMenuControl LeftMenuControl1;
    }
}
