//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.web.Admin {
    
    
    public partial class QuanLyDanhMucThongTinPage {
        
        /// <summary>
        /// AddCatologiesControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::project.web.Controls.AddCatologieControl AddCatologiesControl1;
        
        /// <summary>
        /// ListCatologiesControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::project.web.Controls.ListCatologieControl ListCatologiesControl1;
    }
}
